version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
  authservice:
    image: authservice:latest
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "5248:5248"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5248
      - DOTNET_DataProtection__Path=/app/keys
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__User=user
      - RabbitMQ__Password=password
    volumes:
      - ./AuthService/keys:/app/keys
      - ./AuthService/cert.pfx:/app/cert.pfx
  chatservice:
    image: chatservice:latest
    build:
      dockerfile: src/ChatService/ChatService.API/Dockerfile
    ports:
      - "5104:5104"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5104
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__User=user
      - RabbitMQ__Password=password
