version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=Wwp9NvOlzw
    networks:
      - my_app_network

  rabbitmqtest:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmqtest
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=Wwp9NvOlzw

  authorizationservice:
    image: authorizationservice:latest
    build:
      context: .
      dockerfile: AuthorizationService/Dockerfile
    ports:
      - "5120:5120"
    environment:
      - ASPNETCORE_URLS=http://+:5120
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672

  gatewayservice:
    image: gatewayservice:latest
    build:
      context: .
      dockerfile: src/TaskTracker.Gateway/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - Kestrel__Endpoints__Https__Url=https://localhost:8081
    volumes:
      - ./localhost.pfx:/localhost.pfx

networks:
  my_app_network:
